services:
  frontend:
    image: nginx:1.24.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d

  backend:
    build: .
    command: npm run start
    expose:
      - 5000
    depends_on:
      - json-server

  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3000 -w db.json
    expose:
      - 3000
    volumes:
     - ./data:/data
    restart: always

